version: '3'

services:
  bot-server:
    build:
      context: .
      dockerfile: bot-server/docker/run.Dockerfile
    image: bot-server:latest
    container_name: bot-server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /home/images:/bot-server/images
    ports:
      - 1444:1444
  bot:
    build: 
      context: .
      dockerfile: bot/docker/run.Dockerfile
    image: bot:latest
    container_name: bot
    restart: always
    depends_on:
      db:
        condition: service_started
      bot-server:
        condition: service_started
  bot-admin:
    build:
      context: .
      dockerfile: bot-admin/docker/run.Dockerfile
    image: bot-admin:latest
    container_name: bot-admin
    restart: always
    depends_on:
      bot-server:
        condition: service_started
    ports:
      - 443:443
  bot-webapp:
    build:
      context: .
      dockerfile: bot-webapp/docker/run.Dockerfile
    image: bot-webapp:latest
    container_name: bot-webapp
    restart: always
    depends_on:
      db:
        condition: service_started
    ports:
      - 1445:1445
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
    volumes:
      - pgdata:/var/lib/postgresql@16/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8080:80
  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: ["server", "/data", "--console-address", ":9001"]
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /home/minio/data:/data
volumes:
  pgdata: