version: '3'

services:
  server:
    build:
      context: .
      dockerfile: bot/docker/server.Dockerfile
    image: server:latest
    container_name: server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /home/bot
      - /home/images:/bot/images
    ports:
      - 1444:1444
  bot:
    build: 
      context: .
      dockerfile: bot/docker/bot.Dockerfile
    image: bot:latest
    container_name: bot
    restart: always
    depends_on:
      db:
        condition: service_started
      server:
        condition: service_started
  bot-admin:
    build:
      context: .
      dockerfile: bot-admin/docker/run.Dockerfile
    image: bot-admin:latest
    container_name: bot-admin
    restart: always
    depends_on:
      server:
        condition: service_started
    ports:
      - 443:443
  bot-webapp:
    build:
      context: .
      dockerfile: bot-webapp/docker/run.Dockerfile
    image: bot-webapp:latest
    container_name: bot-webapp
    restart: always
    depends_on:
      db:
        condition: service_started
    ports:
      - 1445:1445
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8080:80
volumes:
  pgdata:
